### ISSUE TITLE
Support for .toml

### ISSUE THREAD

**Issue by Chaitanyabsprip** [b3nj5m1n/kommentary#18]
Kommentary comments lines the wrong way in .toml files. Found the bug while editing my starship prompt config file.

**Comment by b3nj5m1n** [comment]
Hi, thanks for reporting, I'll fix it as soon as possible!

**Comment by b3nj5m1n** [comment]
Should be fixed with 6a448bbaeba2bcf8003e2d4b9da7cf94af262d22, please try it out and close the issue if everything works.

**Comment by Chaitanyabsprip** [comment]
it is still doing line comments with `/* ....*/` it should be same as python with `# ...`

**Comment by b3nj5m1n** [comment]
Did you update the plugin?

**Comment by b3nj5m1n** [comment]
Should be fixed with 7429850d115248bf4d3c4de2e31e5bf47fa1a9ad, I apologise for the inconvenience.

**Comment by Chaitanyabsprip** [comment]
```error
Error detected while processing /home/chaitanya/.local/share/nvim/plugged/kommentary/plugin/kommentary.vim:
line    4:
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'use_default_mappings' (a nil value)
```

**Comment by b3nj5m1n** [comment]
Weird, that hasn't got anything to do with the changes I've made, I would guess that you're running an outdated version of the plugin somehow...

I would suggest reinstalling the plugin and seeing if that fixes the issue.

**Comment by Chaitanyabsprip** [comment]
still is giving the same error and the .toml comment style isn't fixed yet

**Comment by b3nj5m1n** [comment]
It's working fine for me, can you try with this minimal config? (Or provide a minimal config that isn't working for you)
```lua
vim.cmd [[packadd packer.nvim]]
return require('packer').startup(function()
    use 'b3nj5m1n/kommentary'
end)
```
Started with `nvim -u testconfig.lua test.toml` I get this:
![Peek 2021-02-05 22-08](https://user-images.githubusercontent.com/47924309/107089317-b589e780-67fe-11eb-81e5-145eb8e84e15.gif)

**Comment by Chaitanyabsprip** [comment]
I add that in as lua code?

**Comment by b3nj5m1n** [comment]
Create a new file called `testconfig.lua`, put the code from above in there, then start neovim with this command: `nvim -u testconfig.lua test.toml`, which will load nvim with that config instead of your default one. This assumes that you're using packer as your package manager, you might have to adjust this, or just send me a minimal config with your plugin manager, and I'll try to find the issue there.

**Comment by Chaitanyabsprip** [comment]
I installed packer, I made a file testconf.lua, put the above code in it and ran the command `nvim -u testconf.lua test.toml` then I put some text in test.toml and when I press `gcc` it does nothing.

**Comment by b3nj5m1n** [comment]
Did you install the plugin using `PackerInstall`? If you're not usually using Packer, you can just send me a minimal config using the plugin manager of your choice.

**Comment by Chaitanyabsprip** [comment]
I tried it with a minimal config with vim-plug and it works fine.

**Comment by Chaitanyabsprip** [comment]
works fine with my complete config too I don't know what the issue was... :thinking:
